# -*- coding: utf-8 -*-
"""Lab7-Ph65026-Txldl.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nnxgkN_hPj2Sbs2ZqGNwcsxhLym1CTqP
"""

import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy import stats

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import PowerTransformer, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

# =========================
# 1. ĐỌC DỮ LIỆU
# =========================
df = pd.read_csv("ITA105_Lab_7.csv")

print("Kích thước dữ liệu:", df.shape)
print("\n5 dòng đầu:")
print(df.head())

print("\nKiểu dữ liệu:")
print(df.dtypes)

# Chuyển cột ngày để dễ xử lý
if "SaleDate" in df.columns:
    df["SaleDate"] = pd.to_datetime(df["SaleDate"], errors="coerce")
    df["SaleYear"] = df["SaleDate"].dt.year
    df["SaleMonth"] = df["SaleDate"].dt.month

# Các cột số
numeric_cols = df.select_dtypes(include=[np.number]).columns.tolist()

print("\nCác cột số:")
print(numeric_cols)

# =========================
# 2. BÀI 1 - PHÂN TÍCH SKEWNESS
# =========================
print("\n" + "="*60)
print("BÀI 1 - PHÂN TÍCH SKEWNESS")
print("="*60)

skew_table = pd.DataFrame({
    "Column": numeric_cols,
    "Skewness": [df[col].skew() for col in numeric_cols]
})

skew_table["Abs_Skewness"] = skew_table["Skewness"].abs()
skew_table = skew_table.sort_values(by="Abs_Skewness", ascending=False)

top10_skew = skew_table.head(10)

print("\nTop cột lệch nhất:")
print(top10_skew[["Column", "Skewness"]])

# 3 cột lệch mạnh nhất
top3_cols = top10_skew["Column"].head(3).tolist()
print("\n3 cột lệch mạnh nhất:", top3_cols)

# Hàm vẽ Histogram + KDE
def plot_hist_kde(data, col, title_suffix=""):
    plt.figure(figsize=(8, 5))
    plt.hist(data[col].dropna(), bins=30, density=True, alpha=0.6)

    kde = stats.gaussian_kde(data[col].dropna())
    x_vals = np.linspace(data[col].min(), data[col].max(), 300)
    plt.plot(x_vals, kde(x_vals))

    plt.title(f"Histogram + KDE của {col} {title_suffix}")
    plt.xlabel(col)
    plt.ylabel("Density")
    plt.grid(True, alpha=0.3)
    plt.show()

for col in top3_cols:
    plot_hist_kde(df, col, "(trước biến đổi)")

# Mô tả sơ bộ từng cột
print("\nNhận xét skewness:")
for col in top3_cols:
    skew_val = df[col].skew()
    q1 = df[col].quantile(0.25)
    q3 = df[col].quantile(0.75)
    iqr = q3 - q1
    lower = q1 - 1.5 * iqr
    upper = q3 + 1.5 * iqr
    outliers = df[(df[col] < lower) | (df[col] > upper)][col].count()

    if skew_val > 1:
        trend = "lệch phải mạnh"
        suggest = "log / Box-Cox / Power"
    elif skew_val > 0.5:
        trend = "lệch phải vừa"
        suggest = "log hoặc Power"
    elif skew_val < -1:
        trend = "lệch trái mạnh"
        suggest = "Yeo-Johnson / Power"
    elif skew_val < -0.5:
        trend = "lệch trái vừa"
        suggest = "Power"
    else:
        trend = "gần đối xứng"
        suggest = "không cần transform mạnh"

    print(f"\nCột: {col}")
    print(f"  - Skewness: {skew_val:.4f}")
    print(f"  - Xu hướng: {trend}")
    print(f"  - Số outlier (IQR): {outliers}")
    print(f"  - Gợi ý biến đổi: {suggest}")

print("\nTác động tiềm năng của skewness lên mô hình:")
print("- Làm mô hình hồi quy dễ bị ảnh hưởng bởi outlier.")
print("- Làm phân phối dữ liệu không ổn định, tăng nhiễu.")
print("- Có thể làm giảm độ chính xác và khiến hệ số hồi quy kém tin cậy.")
print("- Transform dữ liệu giúp phân phối cân bằng hơn và mô hình học tốt hơn.")

# =========================
# 3. BÀI 2 - BIẾN ĐỔI DỮ LIỆU
# =========================
print("\n" + "="*60)
print("BÀI 2 - BIẾN ĐỔI DỮ LIỆU")
print("="*60)

# Chọn cột theo yêu cầu đề
positive_cols = []
for col in numeric_cols:
    if (df[col] > 0).all():
        positive_cols.append(col)

print("\nCác cột dương hoàn toàn:", positive_cols)

# Chọn 2 cột dương
pos_col1 = "LotArea" if "LotArea" in positive_cols else positive_cols[0]
pos_col2 = "SalePrice" if "SalePrice" in positive_cols else positive_cols[1]

# Chọn 1 cột có âm/0
mixed_candidates = []
for col in numeric_cols:
    if (df[col] <= 0).any():
        mixed_candidates.append(col)

print("Các cột có âm/0:", mixed_candidates)

mixed_col = "MixedFeature" if "MixedFeature" in mixed_candidates else mixed_candidates[0]

print("\nChọn để biến đổi:")
print("Cột dương 1:", pos_col1)
print("Cột dương 2:", pos_col2)
print("Cột âm/0:", mixed_col)

compare_rows = []

def compare_transform_positive(data, col):
    temp = data[[col]].dropna().copy()

    # Log
    temp["log"] = np.log(temp[col])

    # Box-Cox
    boxcox_values, best_lambda = stats.boxcox(temp[col])
    temp["boxcox"] = boxcox_values

    skew_before = temp[col].skew()
    skew_log = temp["log"].skew()
    skew_boxcox = temp["boxcox"].skew()

    compare_rows.append({
        "Column": col,
        "Skew_before": skew_before,
        "Skew_after_Log": skew_log,
        "Skew_after_BoxCox": skew_boxcox,
        "Skew_after_Power": np.nan,
        "Best_Method": "Log" if abs(skew_log) < abs(skew_boxcox) else "Box-Cox",
        "Lambda_BoxCox": best_lambda,
        "Comment": "Cột dương hoàn toàn, phù hợp log và Box-Cox"
    })

    # Vẽ trước - sau
    fig, axes = plt.subplots(1, 3, figsize=(18, 4))

    axes[0].hist(temp[col], bins=30, alpha=0.7)
    axes[0].set_title(f"{col} - Gốc")

    axes[1].hist(temp["log"], bins=30, alpha=0.7)
    axes[1].set_title(f"{col} - Log")

    axes[2].hist(temp["boxcox"], bins=30, alpha=0.7)
    axes[2].set_title(f"{col} - Box-Cox")

    plt.tight_layout()
    plt.show()

    print(f"\nCột {col}")
    print(f"Skew trước: {skew_before:.4f}")
    print(f"Skew sau Log: {skew_log:.4f}")
    print(f"Skew sau Box-Cox: {skew_boxcox:.4f}")
    print(f"Lambda tối ưu Box-Cox: {best_lambda:.4f}")

def compare_transform_mixed(data, col):
    temp = data[[col]].dropna().copy()

    pt = PowerTransformer(method="yeo-johnson")
    temp["power"] = pt.fit_transform(temp[[col]])

    skew_before = temp[col].skew()
    skew_power = temp["power"].skew()

    compare_rows.append({
        "Column": col,
        "Skew_before": skew_before,
        "Skew_after_Log": np.nan,
        "Skew_after_BoxCox": np.nan,
        "Skew_after_Power": skew_power,
        "Best_Method": "Yeo-Johnson Power",
        "Lambda_BoxCox": np.nan,
        "Comment": "Cột có âm/0 nên dùng Yeo-Johnson"
    })

    fig, axes = plt.subplots(1, 2, figsize=(12, 4))

    axes[0].hist(temp[col], bins=30, alpha=0.7)
    axes[0].set_title(f"{col} - Gốc")

    axes[1].hist(temp["power"], bins=30, alpha=0.7)
    axes[1].set_title(f"{col} - Power (Yeo-Johnson)")

    plt.tight_layout()
    plt.show()

    print(f"\nCột {col}")
    print(f"Skew trước: {skew_before:.4f}")
    print(f"Skew sau Power: {skew_power:.4f}")

compare_transform_positive(df, pos_col1)
compare_transform_positive(df, pos_col2)
compare_transform_mixed(df, mixed_col)

compare_df = pd.DataFrame(compare_rows)

print("\nBảng so sánh skewness trước - sau:")
print(compare_df)

print("\nGiải thích λ trong Box-Cox:")
print("- λ là tham số quyết định cách biến đổi dữ liệu.")
print("- λ được chọn sao cho phân phối sau biến đổi gần chuẩn hơn.")
print("- λ khác nhau thì mức độ nén/giãn dữ liệu cũng khác nhau.")

# =========================
# 4. BÀI 3 - ỨNG DỤNG VÀO MÔ HÌNH HÓA
# =========================
print("\n" + "="*60)
print("BÀI 3 - ỨNG DỤNG VÀO MÔ HÌNH HÓA")
print("="*60)

target = "SalePrice"

# Tạo bản dữ liệu riêng cho model
model_df = df.copy()

# Nếu có cột ngày thì tách năm/tháng rồi bỏ cột gốc
if "SaleDate" in model_df.columns:
    model_df["SaleDate"] = pd.to_datetime(model_df["SaleDate"], errors="coerce")
    model_df["SaleYear"] = model_df["SaleDate"].dt.year
    model_df["SaleMonth"] = model_df["SaleDate"].dt.month
    model_df = model_df.drop(columns=["SaleDate"])

X = model_df.drop(columns=[target])
y = model_df[target]

num_features = X.select_dtypes(include=[np.number]).columns.tolist()
cat_features = X.select_dtypes(exclude=[np.number]).columns.tolist()

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

def rmse_score(y_true, y_pred):
    return np.sqrt(mean_squared_error(y_true, y_pred))

# -------- Version A: dữ liệu gốc --------
preprocessor_A = ColumnTransformer([
    ("num", Pipeline([
        ("imputer", SimpleImputer(strategy="median"))
    ]), num_features),

    ("cat", Pipeline([
        ("imputer", SimpleImputer(strategy="most_frequent")),
        ("onehot", OneHotEncoder(handle_unknown="ignore"))
    ]), cat_features)
])

model_A = Pipeline([
    ("preprocessor", preprocessor_A),
    ("regressor", LinearRegression())
])

model_A.fit(X_train, y_train)
pred_A = model_A.predict(X_test)

rmse_A = rmse_score(y_test, pred_A)
r2_A = r2_score(y_test, pred_A)

# -------- Version B: log-transform biến mục tiêu --------
model_B = Pipeline([
    ("preprocessor", preprocessor_A),
    ("regressor", LinearRegression())
])

y_train_log = np.log(y_train)
model_B.fit(X_train, y_train_log)

pred_B_log = model_B.predict(X_test)
pred_B = np.exp(pred_B_log)   # dịch ngược về giá trị thật

rmse_B = rmse_score(y_test, pred_B)
r2_B = r2_score(y_test, pred_B)

# -------- Version C: Power transform các cột skew --------
train_num_skew = X_train.select_dtypes(include=[np.number]).skew()
skewed_cols = train_num_skew[train_num_skew.abs() > 1].index.tolist()
remaining_num_cols = [col for col in num_features if col not in skewed_cols]

print("\nCác cột skew mạnh dùng PowerTransformer:", skewed_cols)

preprocessor_C = ColumnTransformer([
    ("power_num", Pipeline([
        ("imputer", SimpleImputer(strategy="median")),
        ("power", PowerTransformer(method="yeo-johnson"))
    ]), skewed_cols),

    ("num_rest", Pipeline([
        ("imputer", SimpleImputer(strategy="median"))
    ]), remaining_num_cols),

    ("cat", Pipeline([
        ("imputer", SimpleImputer(strategy="most_frequent")),
        ("onehot", OneHotEncoder(handle_unknown="ignore"))
    ]), cat_features)
])

model_C = Pipeline([
    ("preprocessor", preprocessor_C),
    ("regressor", LinearRegression())
])

model_C.fit(X_train, y_train)
pred_C = model_C.predict(X_test)

rmse_C = rmse_score(y_test, pred_C)
r2_C = r2_score(y_test, pred_C)

result_model = pd.DataFrame({
    "Model": ["Version A - Raw", "Version B - Log Target", "Version C - Power Features"],
    "RMSE_test": [rmse_A, rmse_B, rmse_C],
    "R2_test": [r2_A, r2_B, r2_C]
})

print("\nBảng so sánh mô hình:")
print(result_model)

best_model_row = result_model.loc[result_model["RMSE_test"].idxmin()]
print("\nMô hình tốt nhất theo RMSE:")
print(best_model_row)

print("\nPhân tích ảnh hưởng:")
print("- Log-transform ở biến mục tiêu giúp giảm ảnh hưởng của giá trị cực lớn.")
print("- Power transform giúp dữ liệu bớt lệch, giảm tác động của outlier.")
print("- Mô hình ổn định hơn khi dữ liệu đầu vào có phân phối cân bằng hơn.")
print("- Sau khi dự đoán log, cần dùng np.exp() để đưa kết quả về giá trị thật.")

# =========================
# 5. BÀI 4 - INSIGHT NGHIỆP VỤ
# =========================
print("\n" + "="*60)
print("BÀI 4 - INSIGHT NGHIỆP VỤ")
print("="*60)

# Chọn 2 biến lệch mạnh
business_cols = top3_cols[:2]
print("\n2 biến dùng cho phân tích nghiệp vụ:", business_cols)

def transform_for_business(data, col):
    s = data[col].dropna()

    if (s > 0).all():
        transformed = np.log(s)
        method = "log"
    else:
        pt = PowerTransformer(method="yeo-johnson")
        transformed = pt.fit_transform(s.values.reshape(-1, 1)).flatten()
        method = "power"

    return transformed, method

for col in business_cols:
    transformed_values, method = transform_for_business(df, col)

    fig, axes = plt.subplots(1, 2, figsize=(12, 4))

    axes[0].hist(df[col].dropna(), bins=30, alpha=0.7)
    axes[0].set_title(f"{col} - Raw data")

    axes[1].hist(transformed_values, bins=30, alpha=0.7)
    axes[1].set_title(f"{col} - Transform ({method})")

    plt.tight_layout()
    plt.show()

# Tạo metric mới
if "SalePrice" in df.columns and (df["SalePrice"] > 0).all():
    df["log_price_index"] = np.log(df["SalePrice"])
    print("\nĐã tạo metric mới: log_price_index")

    print("\nThống kê log_price_index:")
    print(df["log_price_index"].describe())

print("\nInsight cho người không chuyên:")
print("1. Dữ liệu gốc bị lệch mạnh nên biểu đồ thường dồn về một phía, khó quan sát.")
print("2. Sau khi transform, phân phối trải đều hơn, dễ thấy nhóm phổ biến và điểm bất thường.")
print("3. Điều này giúp hiểu thị trường rõ hơn, ví dụ mức giá phổ biến hay khu vực có giá bất thường.")
print("4. Metric log_price_index có thể dùng để:")
print("   - Phân nhóm khách hàng theo mức giá")
print("   - Phát hiện bất động sản/khu vực có giá cao bất thường")
print("   - Cải thiện mô hình dự báo giá")

print("\nKhuyến nghị kinh doanh:")
print("- Nên transform các biến quá lệch trước khi phân tích nâng cao hoặc xây mô hình.")
print("- Nên theo dõi các điểm outlier để phát hiện sản phẩm/khách hàng đặc biệt.")
print("- Nên dùng dữ liệu đã transform khi muốn so sánh nhóm một cách công bằng hơn.")

skew_table.to_csv("lab7_skewness_ranking.csv", index=False)
compare_df.to_csv("lab7_transform_compare.csv", index=False)
result_model.to_csv("lab7_model_result.csv", index=False)

print("\nĐã lưu file:")
print("- lab7_skewness_ranking.csv")
print("- lab7_transform_compare.csv")
print("- lab7_model_result.csv")